<a href="https://colab.research.google.com/github/valeriamedina2/Evaluacion/blob/main/filtro_california.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Filtro California

In [32]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
#Leemos el codigo 
df= pd.read_csv("valores_nulos_california.csv")
df

,Unnamed: 0,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1,37.770280,-122.433170,3,0.0,1.0,2.0,$202.00,2,...,1 bath,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
1,1,2,37.744740,-122.420890,4,0.0,2.0,2.0,$235.00,30,...,1 bath,2.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",--,t,06/03/2023,03/05/2009,06/08/2017,0,f
2,2,13,37.765550,-122.452130,1,0.0,1.0,1.0,$56.00,32,...,4 shared baths,1.0,"[""Security cameras on property"", ""Host greets ...",--,t,06/03/2023,08/09/2014,27/10/2022,0,f
3,3,2,37.775640,-122.436420,4,0.0,2.0,2.0,$575.00,9,...,1.5 baths,2.0,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",--,t,06/03/2023,25/09/2009,28/06/2019,STR-0000264,f
4,4,2,37.760300,-122.421970,3,0.0,1.0,1.0,$110.00,1,...,1 private bath,1.0,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,6931,9,37.791994,-122.410000,2,0.0,1.0,1.0,$164.00,1,...,1 bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,--,--,147904,t
6932,6932,1,37.763060,-122.432023,2,0.0,1.0,1.0,$228.00,1,...,1 bath,1.0,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",--,t,06/03/2023,03/03/2023,03/03/2023,2023-001477STR,f
6933,6933,1,37.777633,-122.416478,1,0.0,1.0,1.0,$104.00,31,...,1 shared bath,1.0,"[""TV"", ""Free dryer – In unit"", ""Mountain view""...",--,t,06/03/2023,--,--,0,f
6934,6934,3,37.738325,-122.396603,2,0.0,1.0,1.0,$65.00,1,...,1 shared bath,1.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",--,t,06/03/2023,--,--,2022-012562STR,f
6935,6935,2,37.786442,-122.457006,2,0.0,1.0,1.0,$375.00,30,...,1 bath,1.0,"[""Carbon monoxide alarm"", ""Security cameras on...",--,t,06/03/2023,--,--,0,t

##host_acceptance_rate>50%

In [34]:
#No se encuentra esa columnas

##Solo los registros con la categoria "host_is_superhost"

In [35]:
filtro2=df[df["host_is_superhost"] == "t"]
filtro2

,Unnamed: 0,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1,37.770280,-122.433170,3,0.0,1.0,2.0,$202.00,2,...,1 bath,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
4,4,2,37.760300,-122.421970,3,0.0,1.0,1.0,$110.00,1,...,1 private bath,1.0,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
7,7,2,37.717500,-122.396980,2,0.0,1.0,1.0,$95.00,1,...,1.5 shared baths,1.0,"[""Self check-in"", ""Shared BBQ grill: charcoal""...",--,t,06/03/2023,21/02/2010,28/01/2023,2022-011003STR,f
8,8,2,37.771960,-122.434770,5,0.0,3.0,3.0,$425.00,2,...,2 baths,3.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,14/08/2012,19/02/2023,STR-0000192,f
9,9,2,37.785460,-122.461480,6,0.0,3.0,3.0,$545.00,3,...,2 baths,3.0,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",--,t,06/03/2023,05/07/2011,02/01/2022,2022-011317STR,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6913,6913,2,37.719700,-122.463300,2,0.0,1.0,1.0,$71.00,1,...,1 private bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,09/02/2023,13/02/2023,1133735,f
6918,6918,23,37.767920,-122.424256,1,0.0,1.0,1.0,$52.00,30,...,1 shared bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,--,--,0,f
6919,6919,10,37.803929,-122.443176,4,0.0,2.0,2.0,$290.00,30,...,2 baths,2.0,"[""Oven"", ""Security cameras on property"", ""Cook...",--,t,06/03/2023,--,--,0,t
6923,6923,3,37.784690,-122.392874,2,0.0,1.0,1.0,$110.00,30,...,1 bath,1.0,"[""Cooking basics"", ""Blender"", ""Shampoo"", ""TV"",...",--,t,06/03/2023,--,--,0,f
6929,6929,67,37.725231,-122.404776,2,0.0,1.0,1.0,$40.00,120,...,1 shared bath,1.0,"[""Oven"", ""Security cameras on property"", ""Self...",--,t,06/03/2023,--,--,0,f

In [36]:
#Convertir archivo filtrado a CSV
filtro2.to_csv("filtro2california.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro2california.csv")

##"not identity_verified"

In [37]:
filtro3=df[df["host_identity_verified"] == "f"]
filtro3

,Unnamed: 0,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
6,6,1,37.747660,-122.420410,2,0.0,1.0,1.0,$100.00,30,...,1 bath,1.0,"[""Oven"", ""Cooking basics"", ""Blender"", ""Shampoo...",--,t,06/03/2023,22/04/2014,26/11/2022,0,f
28,28,1,37.749160,-122.429710,3,0.0,0.0,2.0,$95.00,30,...,1 bath,0.0,"[""Oven"", ""Cooking basics"", ""Shampoo"", ""Host gr...",--,t,06/03/2023,05/06/2010,19/06/2022,0,f
38,38,1,37.751170,-122.425670,1,0.0,1.0,1.0,$120.00,30,...,Half-bath,1.0,"[""Carbon monoxide alarm"", ""First aid kit"", ""Sm...",--,t,06/03/2023,06/12/2011,22/09/2014,0,f
39,39,1,37.803560,-122.404370,2,0.0,1.0,1.0,$175.00,30,...,1 bath,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,17/05/2018,26/06/2021,0,f
71,71,5,37.792780,-122.410070,10,0.0,1.0,4.0,"$1,000.00",2,...,1 bath,1.0,"[""Essentials"", ""Bed linens"", ""Carbon monoxide ...",--,t,06/03/2023,20/01/2012,23/10/2022,City Registration Pending,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6885,6885,24,37.800850,-122.433658,1,0.0,1.0,1.0,$75.00,30,...,1 shared bath,1.0,"[""Carbon monoxide alarm"", ""Lock on bedroom doo...",--,t,06/03/2023,--,--,0,f
6905,6905,2,37.731587,-122.496157,2,0.0,1.0,1.0,$76.00,1,...,1 bath,1.0,"[""Contact host body soap"", ""Security cameras o...",--,t,06/03/2023,05/02/2023,28/02/2023,2022-013018STR,t
6931,6931,9,37.791994,-122.410000,2,0.0,1.0,1.0,$164.00,1,...,1 bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,--,--,147904,t
6932,6932,1,37.763060,-122.432023,2,0.0,1.0,1.0,$228.00,1,...,1 bath,1.0,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",--,t,06/03/2023,03/03/2023,03/03/2023,2023-001477STR,f
6933,6933,1,37.777633,-122.416478,1,0.0,1.0,1.0,$104.00,31,...,1 shared bath,1.0,"[""TV"", ""Free dryer – In unit"", ""Mountain view""...",--,t,06/03/2023,--,--,0,f

In [38]:
#Convertir archivo filtrado a CSV
filtro3.to_csv("filtro3california.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro3california.csv")

##property_type = "Private room' y 'Hotel Room"

In [39]:
filtro4=df[df["property_type"] == "Private room"]
#filtro4=df[df["property_type"] == "Hotel Room"]
filtro4

,Unnamed: 0,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
7,7,2,37.71750,-122.39698,2,0.0,1.0,1.0,$95.00,1,...,1.5 shared baths,1.0,"[""Self check-in"", ""Shared BBQ grill: charcoal""...",--,t,06/03/2023,21/02/2010,28/01/2023,2022-011003STR,f
1575,1575,3,37.75145,-122.40719,2,0.0,1.0,0.0,$69.00,30,...,1 shared bath,1.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",--,t,06/03/2023,11/08/2016,01/11/2020,City registration pending,t
2049,2049,7,37.79586,-122.41915,2,0.0,0.0,1.0,$60.00,30,...,1 private bath,0.0,"[""Free street parking"", ""Dishes and silverware...",--,t,06/03/2023,09/12/2017,17/01/2023,0,t
4014,4014,7,37.79525,-122.41931,1,0.0,0.0,1.0,$56.00,30,...,1 bath,0.0,"[""Essentials"", ""Dishes and silverware"", ""Coffe...",--,t,06/03/2023,28/02/2022,09/12/2022,0,f

In [40]:
#Convertir archivo filtrado a CSV
filtro4.to_csv("filtro4california.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro4california.csv")

##bathroom>1

In [41]:
#Filtro por comparacion
filtro5=df[df["bathrooms"] > 1]
filtro5

Empty DataFrame
Columns: [Unnamed: 0, host_listings_count, latitude, longitude, accommodates, bathrooms, bedrooms, beds, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, availability_365, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, ï»¿id, listing_url, scrape_id, last_scraped, source, name, description, neighborhood_overview, picture_url, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_is_superhost, host_thumbnail_url, host_picture_url, host_neighbourhood, host_verifications, host_has_profile_pic, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, property_type, room_type, bathrooms.1, bathrooms_text, bedrooms.1, amenities, calendar_updated.1, has_availability, calendar_last_scraped, first_review, last_review, license, instant_bookable]
Index: []

[0 rows x 76 columns]

In [42]:
#Convertir archivo filtrado a CSV
filtro5.to_csv("filtro5california.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro5california.csv")

##Precio mayor de 10000 y que sean de tipo "Entire Home"

In [43]:
filtro6=df[(df["price"] > "10000") & (df["room_type"] == "Entire Home/apt")]
filtro6

Empty DataFrame
Columns: [Unnamed: 0, host_listings_count, latitude, longitude, accommodates, bathrooms, bedrooms, beds, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, availability_365, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, ï»¿id, listing_url, scrape_id, last_scraped, source, name, description, neighborhood_overview, picture_url, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_is_superhost, host_thumbnail_url, host_picture_url, host_neighbourhood, host_verifications, host_has_profile_pic, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, property_type, room_type, bathrooms.1, bathrooms_text, bedrooms.1, amenities, calendar_updated.1, has_availability, calendar_last_scraped, first_review, last_review, license, instant_bookable]
Index: []

[0 rows x 76 columns]

##registros review_scores_cleanliness>4.5

In [44]:
filtro7=df[df["review_scores_cleanliness"] > 4.5]
filtro7

,Unnamed: 0,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1,37.770280,-122.433170,3,0.0,1.0,2.0,$202.00,2,...,1 bath,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
1,1,2,37.744740,-122.420890,4,0.0,2.0,2.0,$235.00,30,...,1 bath,2.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",--,t,06/03/2023,03/05/2009,06/08/2017,0,f
3,3,2,37.775640,-122.436420,4,0.0,2.0,2.0,$575.00,9,...,1.5 baths,2.0,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",--,t,06/03/2023,25/09/2009,28/06/2019,STR-0000264,f
4,4,2,37.760300,-122.421970,3,0.0,1.0,1.0,$110.00,1,...,1 private bath,1.0,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
5,5,1,37.784400,-122.479320,4,0.0,2.0,2.0,$259.00,5,...,1 bath,2.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,21/10/2011,17/02/2023,STR-0002192,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6924,6924,7,37.716079,-122.390953,2,0.0,1.0,1.0,$79.00,1,...,1.5 shared baths,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,07/02/2023,07/02/2023,2022-012006STR,f
6925,6925,7,37.716214,-122.391460,2,0.0,1.0,1.0,$85.00,1,...,1.5 shared baths,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,10/02/2023,24/02/2023,2022-012006STR,f
6926,6926,7,37.716070,-122.391170,2,0.0,1.0,1.0,$83.00,1,...,1.5 shared baths,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,03/02/2023,25/02/2023,2022-012006STR,f
6927,6927,32,37.788619,-122.422556,2,0.0,1.0,1.0,$80.00,1,...,1 private bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,13/02/2023,13/02/2023,Exempt,f
6932,6932,1,37.763060,-122.432023,2,0.0,1.0,1.0,$228.00,1,...,1 bath,1.0,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",--,t,06/03/2023,03/03/2023,03/03/2023,2023-001477STR,f

In [45]:
#Convertir archivo filtrado a CSV
filtro7.to_csv("filtro7california.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro7california.csv")

##registros review_scores_value>4.9

In [46]:
filtro8=df[df["review_scores_value"] > 4.9]
filtro8

,Unnamed: 0,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
9,9,2,37.785460,-122.461480,6,0.0,3.0,3.0,$545.00,3,...,2 baths,3.0,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",--,t,06/03/2023,05/07/2011,02/01/2022,2022-011317STR,f
24,24,2,37.762160,-122.450220,2,0.0,1.0,1.0,$180.00,30,...,1 bath,1.0,"[""Oven"", ""Security cameras on property"", ""Cook...",--,t,06/03/2023,01/08/2014,14/02/2023,0,f
26,26,1,37.762370,-122.429920,2,0.0,1.0,1.0,$99.00,3,...,1.5 shared baths,1.0,"[""Essentials"", ""Bed linens"", ""Dishes and silve...",--,t,06/03/2023,14/01/2010,20/02/2023,STR-0000057,f
46,46,2,37.717270,-122.436440,1,0.0,1.0,1.0,$85.00,2,...,1.5 shared baths,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""S...",--,t,06/03/2023,20/05/2018,31/01/2023,STR-0003035,t
53,53,1,37.744030,-122.417550,2,0.0,2.0,2.0,$80.00,4,...,1 shared bath,2.0,"[""Oven"", ""Cooking basics"", ""Blender"", ""Shampoo...",--,t,06/03/2023,23/07/2012,01/03/2023,STR-0001006,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6920,6920,9,37.801789,-122.426501,2,0.0,1.0,1.0,$107.00,1,...,1 private bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,10/02/2023,10/02/2023,Exempt,t
6924,6924,7,37.716079,-122.390953,2,0.0,1.0,1.0,$79.00,1,...,1.5 shared baths,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,07/02/2023,07/02/2023,2022-012006STR,f
6925,6925,7,37.716214,-122.391460,2,0.0,1.0,1.0,$85.00,1,...,1.5 shared baths,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,10/02/2023,24/02/2023,2022-012006STR,f
6927,6927,32,37.788619,-122.422556,2,0.0,1.0,1.0,$80.00,1,...,1 private bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,13/02/2023,13/02/2023,Exempt,f
6932,6932,1,37.763060,-122.432023,2,0.0,1.0,1.0,$228.00,1,...,1 bath,1.0,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",--,t,06/03/2023,03/03/2023,03/03/2023,2023-001477STR,f

In [47]:
#Convertir archivo filtrado a CSV
filtro8.to_csv("filtro8california.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro8california.csv")

##availability_365<100

In [48]:
filtro9=df[df["availability_365"] < 100]
filtro9

,Unnamed: 0,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
5,5,1,37.784400,-122.479320,4,0.0,2.0,2.0,$259.00,5,...,1 bath,2.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,21/10/2011,17/02/2023,STR-0002192,f
8,8,2,37.771960,-122.434770,5,0.0,3.0,3.0,$425.00,2,...,2 baths,3.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,14/08/2012,19/02/2023,STR-0000192,f
9,9,2,37.785460,-122.461480,6,0.0,3.0,3.0,$545.00,3,...,2 baths,3.0,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",--,t,06/03/2023,05/07/2011,02/01/2022,2022-011317STR,f
11,11,9,37.792330,-122.424310,1,0.0,1.0,1.0,$55.00,30,...,--,1.0,"[""Essentials"", ""Bed linens"", ""Carbon monoxide ...",--,t,06/03/2023,10/07/2011,28/02/2023,0,f
15,15,5,37.772520,-122.438460,2,0.0,1.0,1.0,$220.00,30,...,1 bath,1.0,"[""TV with standard cable, DVD player, HBO Max""...",--,t,06/03/2023,27/06/2012,26/09/2022,0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6913,6913,2,37.719700,-122.463300,2,0.0,1.0,1.0,$71.00,1,...,1 private bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,09/02/2023,13/02/2023,1133735,f
6917,6917,1,37.748247,-122.433441,2,0.0,1.0,1.0,$222.00,2,...,1 bath,1.0,"[""Oven"", ""Security cameras on property"", ""Self...",--,t,06/03/2023,--,--,2023-001339STR,f
6918,6918,23,37.767920,-122.424256,1,0.0,1.0,1.0,$52.00,30,...,1 shared bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,--,--,0,f
6923,6923,3,37.784690,-122.392874,2,0.0,1.0,1.0,$110.00,30,...,1 bath,1.0,"[""Cooking basics"", ""Blender"", ""Shampoo"", ""TV"",...",--,t,06/03/2023,--,--,0,f
6931,6931,9,37.791994,-122.410000,2,0.0,1.0,1.0,$164.00,1,...,1 bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,--,--,147904,t

In [49]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("filtro9california.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro9california.csv")

##host_response_time sea "within an hour"

In [50]:
filtro10=df[df["host_response_time"] == "within an hour"]
filtro10

,Unnamed: 0,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1,37.770280,-122.433170,3,0.0,1.0,2.0,$202.00,2,...,1 bath,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
2,2,13,37.765550,-122.452130,1,0.0,1.0,1.0,$56.00,32,...,4 shared baths,1.0,"[""Security cameras on property"", ""Host greets ...",--,t,06/03/2023,08/09/2014,27/10/2022,0,f
4,4,2,37.760300,-122.421970,3,0.0,1.0,1.0,$110.00,1,...,1 private bath,1.0,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
5,5,1,37.784400,-122.479320,4,0.0,2.0,2.0,$259.00,5,...,1 bath,2.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/2023,21/10/2011,17/02/2023,STR-0002192,f
12,12,2,37.728330,-122.441250,2,0.0,1.0,1.0,$235.00,4,...,1 bath,1.0,"[""Oven"", ""Cooking basics"", ""Shampoo"", ""Host gr...",--,t,06/03/2023,17/06/2012,25/10/2022,STR-0004820,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6929,6929,67,37.725231,-122.404776,2,0.0,1.0,1.0,$40.00,120,...,1 shared bath,1.0,"[""Oven"", ""Security cameras on property"", ""Self...",--,t,06/03/2023,--,--,0,f
6930,6930,6,37.753771,-122.399004,1,0.0,1.0,1.0,$56.00,30,...,1 shared bath,1.0,"[""Carbon monoxide alarm"", ""Security cameras on...",--,t,06/03/2023,--,--,0,t
6931,6931,9,37.791994,-122.410000,2,0.0,1.0,1.0,$164.00,1,...,1 bath,1.0,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/2023,--,--,147904,t
6934,6934,3,37.738325,-122.396603,2,0.0,1.0,1.0,$65.00,1,...,1 shared bath,1.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",--,t,06/03/2023,--,--,2022-012562STR,f
6935,6935,2,37.786442,-122.457006,2,0.0,1.0,1.0,$375.00,30,...,1 bath,1.0,"[""Carbon monoxide alarm"", ""Security cameras on...",--,t,06/03/2023,--,--,0,t

In [51]:
#Convertir archivo filtrado a CSV
filtro10.to_csv("filtro10california.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro10california.csv")