<a href="https://colab.research.google.com/github/valeriamedina2/Evaluacion/blob/main/filtro_espa%C3%B1a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Filtro España

In [64]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
#Leemos el codigo 
df= pd.read_csv("valores_nulos_españa.csv")
df

<ipython-input-65-7e828c155980>:2: DtypeWarning: Columns (0,1,3,4,5,6,7,8,10,11,12,13,15,17,19,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("valores_nulos_españa.csv")

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,14551.0,1.0,41.9965,2.83646,2,0.0,1.0,1.0,$42.00,...,1 private bath,1.0,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",--,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
1,1,1205757.0,1.0,41.79304,2.77412,2,0.0,1.0,1.0,$47.00,...,1.5 shared baths,1.0,"[""Free parking on premises"", ""Refrigerator"", ""...",--,t,31/03/2023,01/08/2013,26/06/2022,0,f
2,2,1212820.0,2.0,42.11284,3.1667,4,0.0,1.0,2.0,$74.00,...,1 bath,1.0,"[""Air conditioning"", ""Free parking on premises...",--,t,01/04/2023,10/06/2013,30/12/2022,0,f
3,3,751638.0,6.0,42.36958,2.9803,2,0.0,1.0,2.0,$45.00,...,1 private bath,1.0,"[""Hair dryer"", ""Luggage dropoff allowed"", ""Fre...",--,t,31/03/2023,23/08/2013,29/08/2022,PG000794,t
4,4,41342.0,2.0,42.34655,3.20463,4,0.0,1.0,1.0,$120.00,...,1 bath,1.0,"[""Free parking on premises"", ""Refrigerator"", ""...",--,t,01/04/2023,14/07/2013,28/08/2021,HUTG-003688,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19651,19650,858387000000000000.0,34.0,41.957265,3.201288,8,0.0,4.0,0.0,$209.00,...,5 baths,4.0,"[""Pets allowed"", ""Smoking allowed"", ""Essentials""]",--,t,01/04/2023,--,--,HUTG-001292,t
19652,19651,858396000000000000.0,3.0,41.69907,2.84408,4,0.0,1.0,1.0,$52.00,...,1 bath,1.0,"[""Kitchen"", ""Pets allowed"", ""Washer""]",--,t,01/04/2023,--,--,HUTG019727,t
19653,19652,858411000000000000.0,9.0,41.81372,3.064465,4,0.0,2.0,3.0,$66.00,...,1 bath,2.0,"[""Kitchen"", ""Free street parking"", ""Washer"", ""...",--,t,01/04/2023,--,--,HUTG-057830,f
19654,19653,858418000000000000.0,111.0,41.809375,3.05391,4,0.0,2.0,3.0,$108.00,...,1 bath,2.0,"[""Refrigerator"", ""Microwave"", ""Elevator"", ""Pet...",--,t,01/04/2023,--,--,HUTG-065236,t
19655,19654,858424000000000000.0,9.0,41.810169,3.066358,5,0.0,3.0,3.0,$73.00,...,1 bath,3.0,"[""Kitchen"", ""Washer"", ""Clothing storage"", ""Dis...",--,t,01/04/2023,--,--,HUTG-051787,f

##host_acceptance_rate>50%

##Solo los registros con la categoria "host_is_superhost"

In [66]:
filtro2=df[df["host_is_superhost"] == "t"]
filtro2

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,14551.0,1.0,41.9965,2.83646,2,0.0,1.0,1.0,$42.00,...,1 private bath,1.0,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",--,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
8,8,45400.0,1.0,41.95577,3.21096,4,0.0,1.0,2.0,$83.00,...,1 bath,1.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""E...",--,t,01/04/2023,28/12/2010,04/03/2023,HUTG-015895,t
10,10,753604.0,7.0,41.7173,2.86409,6,0.0,3.0,4.0,$195.00,...,1 bath,3.0,"[""Carbon monoxide alarm"", ""Free parking on pre...",--,t,01/04/2023,08/09/2013,03/09/2022,LLG-000010,f
21,21,106704.0,5.0,41.83631,2.937,12,0.0,4.0,12.0,$231.00,...,4.5 baths,4.0,"[""Dedicated workspace"", ""Kitchen"", ""Self check...",--,t,01/04/2023,19/07/2011,31/12/2022,PG-002599,f
23,23,766763.0,2.0,41.96041,3.22659,12,0.0,5.0,12.0,$399.00,...,3 baths,5.0,"[""Carbon monoxide alarm"", ""Free parking on pre...",--,t,01/04/2023,04/06/2016,16/10/2022,HUTG-043628,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19598,19597,857006000000000000.0,15.0,42.29087,3.2764,6,0.0,3.0,4.0,$341.00,...,3 baths,3.0,"[""Air conditioning"", ""Free parking on premises...",--,t,01/04/2023,--,--,HUTG-060488,t
19602,19601,856171000000000000.0,5.0,42.05427,3.20685,6,0.0,3.0,3.0,$230.00,...,1.5 baths,3.0,"[""Refrigerator"", ""Microwave"", ""Safe"", ""Free st...",--,t,01/04/2023,--,--,HUTG-059959,f
19618,19617,857140000000000000.0,19.0,42.291029,3.278916,4,0.0,2.0,3.0,$170.00,...,1 bath,2.0,"[""Dedicated workspace"", ""Kitchen"", ""Air condit...",--,t,31/03/2023,--,--,HUTG-060928,t
19629,19628,857697000000000000.0,10.0,41.78785,3.02869,6,0.0,3.0,3.0,$207.00,...,2 baths,3.0,"[""Air conditioning"", ""Free parking on premises...",--,t,01/04/2023,--,--,HUTG-067564,t
19652,19651,858396000000000000.0,3.0,41.69907,2.84408,4,0.0,1.0,1.0,$52.00,...,1 bath,1.0,"[""Kitchen"", ""Pets allowed"", ""Washer""]",--,t,01/04/2023,--,--,HUTG019727,t

In [67]:
#Convertir archivo filtrado a CSV
filtro2.to_csv("filtro2españa.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro2españa.csv")

##"not identity_verified"

In [68]:
filtro3=df[df["host_identity_verified"] == "f"]
filtro3

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
2,2,1212820.0,2.0,42.11284,3.1667,4,0.0,1.0,2.0,$74.00,...,1 bath,1.0,"[""Air conditioning"", ""Free parking on premises...",--,t,01/04/2023,10/06/2013,30/12/2022,0,f
7,7,1215790.0,1.0,41.84984,3.1265,7,0.0,3.0,5.0,$60.00,...,2 baths,3.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""F...",--,t,01/04/2023,01/07/2013,18/02/2018,HUTG-017955,f
9,9,1222762.0,1.0,42.21904,2.90744,5,0.0,3.0,4.0,$65.00,...,2 baths,3.0,"[""Heating"", ""Kitchen"", ""Air conditioning"", ""Wa...",--,t,31/03/2023,19/08/2013,14/09/2022,HUTG-012585,f
30,30,784892.0,1.0,42.39611,1.91888,6,0.0,3.0,7.0,$100.00,...,3 baths,3.0,"[""Shared pool"", ""Free parking on premises"", ""R...",--,t,31/03/2023,11/09/2015,11/09/2015,0,f
33,33,1242933.0,1.0,41.85578,3.13043,4,0.0,2.0,3.0,$100.00,...,1 bath,2.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Oven"", ""Dis...",--,t,01/04/2023,02/08/2013,29/07/2019,HUTG-019098,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19554,19553,856453000000000000.0,4.0,41.81861,3.056453,4,0.0,2.0,3.0,$182.00,...,1.5 baths,2.0,"[""Air conditioning"", ""Stainless steel oven"", ""...",--,t,01/04/2023,--,--,HUTG-029538,f
19561,19560,855549000000000000.0,1.0,41.69185,2.81279,8,0.0,4.0,5.0,$134.00,...,3 baths,4.0,"[""Free parking on premises"", ""Refrigerator"", ""...",--,t,01/04/2023,--,--,HUTG002307,t
19562,19561,856490000000000000.0,30.0,42.26445,3.1793,5,0.0,2.0,4.0,$168.00,...,1 bath,2.0,"[""Air conditioning"", ""Free parking on premises...",--,t,01/04/2023,--,--,HUTG-023155,t
19612,19611,857116000000000000.0,14.0,41.7945,3.04349,7,0.0,3.0,5.0,$161.00,...,2 baths,3.0,"[""Iron"", ""Ethernet connection"", ""Single level ...",--,t,01/04/2023,--,--,HUTG-008448,t
19613,19612,857118000000000000.0,14.0,41.79446,3.04403,7,0.0,3.0,5.0,$161.00,...,--,3.0,"[""Iron"", ""Dishwasher"", ""Washer"", ""Bathtub"", ""H...",--,t,01/04/2023,--,--,HUTG-008448,t

In [85]:
#Convertir archivo filtrado a CSV
filtro3.to_csv("filtro3españa.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro3españa.csv")

##property_type = "Private room' y 'Hotel Room"

In [70]:
filtro4=df[df["property_type"] == "Private room"]
#filtro4=df[df["property_type"] == "Hotel Room"]
filtro4

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
356,356,3054347.0,2.0,42.28732,3.27713,2,0.0,0.0,1.0,$109.00,...,1 private bath,0.0,"[""Air conditioning"", ""Refrigerator"", ""Shampoo""...",--,t,01/04/2023,16/06/2014,05/11/2022,HUTG-002595,f
2485,2484,14613107.0,1.0,42.15369,2.60122,4,0.0,1.0,2.0,$40.00,...,1 bath,1.0,"[""Hair dryer"", ""Iron"", ""Washer"", ""Free parking...",--,t,01/04/2023,02/10/2016,15/10/2017,0,f
3135,3134,17117682.0,10.0,42.1448,2.56848,2,0.0,1.0,2.0,$73.00,...,1 private bath,1.0,"[""Pool"", ""Pets allowed"", ""Hangers"", ""Heating"",...",--,t,31/03/2023,25/02/2017,05/12/2022,ATG-000023,f
7839,7838,32997174.0,1.0,42.15973,2.91132,2,0.0,1.0,1.0,$40.00,...,1 bath,1.0,"[""Sanex body soap"", ""Microwave"", ""First aid ki...",--,t,31/03/2023,16/08/2020,22/08/2022,Exempt,f
16666,16665,658305000000000000.0,1.0,41.72831,2.919324,2,0.0,1.0,1.0,$50.00,...,1.5 baths,1.0,"[""Carbon monoxide alarm"", ""Refrigerator"", ""Lon...",--,t,01/04/2023,17/07/2022,22/07/2022,HUTB-123456,t
17058,17057,686738000000000000.0,1.0,42.18328,2.88674,2,0.0,1.0,1.0,$120.00,...,1 private bath,1.0,"[""Free parking on premises"", ""Shared outdoor p...",--,t,31/03/2023,--,--,Exempt,f
19023,19022,841209000000000000.0,2.0,42.30333,2.16657,2,0.0,1.0,1.0,$80.00,...,1 private bath,1.0,"[""Clothing storage: walk-in closet"", ""Pack ’n ...",--,t,01/04/2023,--,--,Exempt,t

In [84]:
#Convertir archivo filtrado a CSV
filtro4.to_csv("filtro4españa.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro4españa.csv")

##bathroom>1

In [86]:
#Filtro por comparacion
filtro5=df[df["bathrooms"] == "1"]
filtro5

Empty DataFrame
Columns: [Unnamed: 0, id, host_listings_count, latitude, longitude, accommodates, bathrooms, bedrooms, beds, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, availability_365, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, id.1, listing_url, scrape_id, last_scraped, source, name, description, neighborhood_overview, picture_url, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_is_superhost, host_thumbnail_url, host_picture_url, host_neighbourhood, host_verifications, host_has_profile_pic, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, property_type, room_type, bathrooms.1, bathrooms_text, bedrooms.1, amenities, calendar_updated.1, has_availability, calendar_last_scraped, first_review, last_review, license, instant_bookable]
Index: []

[0 rows x 77 columns]

In [73]:
#Convertir archivo filtrado a CSV
filtro5.to_csv("filtro5españa.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro5españa.csv")

##Precio mayor de 10000 y que sean de tipo "Entire Home"

In [74]:
filtro6=df[(df["price"] > "10000") & (df["room_type"] == "Entire Home/apt")]
filtro6

Empty DataFrame
Columns: [Unnamed: 0, id, host_listings_count, latitude, longitude, accommodates, bathrooms, bedrooms, beds, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, availability_365, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, id.1, listing_url, scrape_id, last_scraped, source, name, description, neighborhood_overview, picture_url, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_is_superhost, host_thumbnail_url, host_picture_url, host_neighbourhood, host_verifications, host_has_profile_pic, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, property_type, room_type, bathrooms.1, bathrooms_text, bedrooms.1, amenities, calendar_updated.1, has_availability, calendar_last_scraped, first_review, last_review, license, instant_bookable]
Index: []

[0 rows x 77 columns]

In [87]:
#Convertir archivo filtrado a CSV
filtro6.to_csv("filtro6españa.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro6españa.csv")

##registros review_scores_cleanliness>4.5

In [76]:
filtro7=df[df["review_scores_cleanliness"] > 4.5]
filtro7

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,14551.0,1.0,41.9965,2.83646,2,0.0,1.0,1.0,$42.00,...,1 private bath,1.0,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",--,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
1,1,1205757.0,1.0,41.79304,2.77412,2,0.0,1.0,1.0,$47.00,...,1.5 shared baths,1.0,"[""Free parking on premises"", ""Refrigerator"", ""...",--,t,31/03/2023,01/08/2013,26/06/2022,0,f
4,4,41342.0,2.0,42.34655,3.20463,4,0.0,1.0,1.0,$120.00,...,1 bath,1.0,"[""Free parking on premises"", ""Refrigerator"", ""...",--,t,01/04/2023,14/07/2013,28/08/2021,HUTG-003688,f
5,5,751997.0,12.0,41.91798,3.16419,4,0.0,1.0,2.0,$105.00,...,1 bath,1.0,"[""Air conditioning"", ""Pack ’n play/Travel crib...",--,t,01/04/2023,03/05/2016,26/02/2023,HUTG-016218,t
6,6,752035.0,12.0,41.91801,3.17085,4,0.0,2.0,2.0,$110.00,...,1 bath,2.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",--,t,31/03/2023,02/07/2013,31/10/2021,HUTG-008974,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18962,18961,832731000000000000.0,1.0,42.18404,2.4629,6,0.0,3.0,4.0,$86.00,...,2 baths,3.0,"[""Free residential garage on premises – 1 spac...",--,t,31/03/2023,12/03/2023,26/03/2023,HUTG-066752,t
19002,19001,841060000000000000.0,1.0,41.72051,2.93222,4,0.0,1.0,2.0,$106.00,...,1 bath,1.0,"[""Stainless steel oven"", ""Refrigerator"", ""Outd...",--,t,01/04/2023,20/03/2023,20/03/2023,HUTG-048774,t
19047,19046,841674000000000000.0,2.0,42.252803,3.105931,4,0.0,1.0,2.0,$59.00,...,1 bath,1.0,"[""Carbon monoxide alarm"", ""Free parking on pre...",--,t,01/04/2023,26/03/2023,26/03/2023,Exempt,t
19078,19077,841996000000000000.0,2.0,42.24757,3.10449,2,0.0,1.0,1.0,$39.00,...,1 shared bath,1.0,"[""Hair dryer"", ""Dedicated workspace"", ""Air con...",--,t,01/04/2023,15/03/2023,15/03/2023,HUTG-047773,f
19203,19202,842711000000000000.0,1.0,42.246529,3.127426,4,0.0,1.0,3.0,$80.00,...,1 bath,1.0,"[""Central air conditioning"", ""Refrigerator"", ""...",--,t,01/04/2023,12/03/2023,17/03/2023,HUTG-027175,f

In [77]:
#Convertir archivo filtrado a CSV
filtro7.to_csv("filtro7españa.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro7españa.csv")

##registros review_scores_value>4.9

In [78]:
filtro8=df[df["review_scores_value"] > 4.9]
filtro8

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
22,22,1234785.0,2.0,41.95188,3.20297,6,0.0,3.0,4.0,$335.00,...,2.5 baths,3.0,"[""Shared pool"", ""Free parking on premises"", ""R...",--,t,01/04/2023,30/08/2021,25/08/2022,HUTG-026895,f
26,26,774371.0,2.0,41.84428,3.10006,5,0.0,2.0,4.0,$60.00,...,2 baths,2.0,"[""Central air conditioning"", ""Refrigerator"", ""...",--,t,01/04/2023,22/01/2017,10/09/2022,HUTG-014853,f
40,40,1250062.0,1.0,41.82205,3.06874,8,0.0,4.0,6.0,$303.00,...,2.5 baths,4.0,"[""Shared pool"", ""Courtyard view"", ""Free parkin...",--,t,01/04/2023,03/08/2021,21/07/2022,HUTG-025234,f
43,43,809136.0,35.0,42.10369,3.0823,4,0.0,2.0,2.0,$108.00,...,1 bath,2.0,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",--,t,31/03/2023,09/04/2015,01/06/2019,HUTG-001370,t
53,53,1262051.0,7.0,42.20932,2.73697,4,0.0,1.0,2.0,$73.00,...,1 bath,1.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",--,t,31/03/2023,01/05/2016,04/11/2018,ATG-000053,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19039,19038,841317000000000000.0,2.0,42.340474,1.9581,2,0.0,1.0,1.0,$70.00,...,1 bath,1.0,"[""Free parking on premises"", ""Refrigerator"", ""...",--,t,31/03/2023,26/03/2023,26/03/2023,HUTG-063362,f
19047,19046,841674000000000000.0,2.0,42.252803,3.105931,4,0.0,1.0,2.0,$59.00,...,1 bath,1.0,"[""Carbon monoxide alarm"", ""Free parking on pre...",--,t,01/04/2023,26/03/2023,26/03/2023,Exempt,t
19078,19077,841996000000000000.0,2.0,42.24757,3.10449,2,0.0,1.0,1.0,$39.00,...,1 shared bath,1.0,"[""Hair dryer"", ""Dedicated workspace"", ""Air con...",--,t,01/04/2023,15/03/2023,15/03/2023,HUTG-047773,f
19203,19202,842711000000000000.0,1.0,42.246529,3.127426,4,0.0,1.0,3.0,$80.00,...,1 bath,1.0,"[""Central air conditioning"", ""Refrigerator"", ""...",--,t,01/04/2023,12/03/2023,17/03/2023,HUTG-027175,f
19468,19467,850041000000000000.0,1.0,41.974072,2.789637,3,0.0,1.0,1.0,$22.00,...,1 shared bath,1.0,"[""Dedicated workspace"", ""Mountain view"", ""Iron...",--,t,01/04/2023,23/03/2023,26/03/2023,HUTS-201920,t

In [79]:
#Convertir archivo filtrado a CSV
filtro8.to_csv("filtro8españa.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro8españa.csv")

##availability_365<100

In [80]:
filtro9=df[df["availability_365"] == "100"]
filtro9

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
327,327,2661094.0,1.0,41.97568,3.16982,12,0.0,6.0,9.0,$347.00,...,4 baths,6.0,"[""Carbon monoxide alarm"", ""Free parking on pre...",--,t,31/03/2023,02/06/2014,28/10/2022,HUTG-006972,f
463,463,3153346.0,2.0,42.01749,2.92635,2,0.0,1.0,1.0,$119.00,...,1 bath,1.0,"[""Air conditioning"", ""Free parking on premises...",--,t,31/03/2023,26/08/2017,26/03/2023,PG-000873,f
789,789,5064630.0,16.0,42.26163,3.151,4,0.0,1.0,1.0,$70.00,...,1 bath,1.0,"[""Shared pool"", ""Refrigerator"", ""Beach view"", ...",--,t,01/04/2023,15/08/2015,06/08/2022,HUTG-003684,f
1310,1309,7863974.0,112.0,41.8871,3.18066,4,0.0,2.0,3.0,$108.00,...,1 bath,2.0,"[""Refrigerator"", ""Host greets you"", ""Private e...",--,t,01/04/2023,08/05/2016,16/09/2021,HUTG-006471,t
1678,1677,11201038.0,1.0,41.97407,3.1772,6,0.0,3.0,4.0,$225.00,...,2 baths,3.0,"[""Free parking on premises"", ""Stainless steel ...",--,t,31/03/2023,16/07/2016,03/09/2022,Exempt,f
2468,2467,14559752.0,29.0,41.94242,3.20066,4,0.0,2.0,3.0,$170.00,...,1 bath,2.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",--,t,01/04/2023,28/08/2018,05/08/2022,HUTG-014045,f
2496,2495,15125278.0,419.0,42.04983,3.16698,8,0.0,3.0,6.0,$143.00,...,2 baths,3.0,"[""Free parking on premises"", ""Refrigerator"", ""...",--,t,01/04/2023,01/01/2018,22/05/2022,HUTG-011767,t
2985,2984,16957948.0,163.0,42.26379,3.18634,6,0.0,3.0,6.0,$100.00,...,2 baths,3.0,"[""Pool"", ""Kitchen"", ""Freezer"", ""Oven"", ""Washer...",--,t,01/04/2023,18/06/2018,16/06/2022,HUTG010226,t
3008,3007,16957969.0,163.0,42.26553,3.16606,4,0.0,2.0,4.0,$100.00,...,1 bath,2.0,"[""Kitchen"", ""Freezer"", ""Washer"", ""Hangers"", ""B...",--,t,01/04/2023,--,--,HUTG007524,t
3294,3293,17374643.0,97.0,42.00847,3.19184,6,0.0,3.0,5.0,$92.00,...,2.5 baths,3.0,"[""Refrigerator"", ""Microwave"", ""Pets allowed"", ...",--,t,01/04/2023,27/07/2018,14/08/2021,HUTG-012112,t
3332,3331,17731166.0,120.0,41.94057,3.21122,5,0.0,3.0,4.0,$131.00,...,2 baths,3.0,"[""Pool"", ""Kitchen"", ""Oven"", ""Dishwasher"", ""Was...",--,t,01/04/2023,--,--,HUTG-021078,t
3944,3943,18928668.0,28.0,41.82087,3.01392,6,0.0,3.0,5.0,$197.00,...,3 baths,3.0,"[""Air conditioning"", ""Sound system"", ""Refriger...",--,t,31/03/2023,--,--,HUTG-8206,t
3985,3984,18804324.0,151.0,41.96065,3.21004,6,0.0,3.0,4.0,$420.00,...,2.5 baths,3.0,"[""Shared pool"", ""Free parking on premises"", ""P...",--,t,01/04/2023,18/08/2017,09/07/2022,HUTG-027424,t
4072,4071,19024820.0,91.0,42.26647,3.17522,9,0.0,4.0,7.0,$80.00,...,2 baths,4.0,"[""Kitchen"", ""Iron"", ""Freezer"", ""Oven"", ""Washer...",--,t,01/04/2023,27/07/2019,13/08/2022,HUTG-013790-90,t
5028,5027,21571348.0,79.0,41.78832,3.02641,8,0.0,4.0,6.0,$175.00,...,2 baths,4.0,"[""Pool"", ""Kitchen"", ""Iron"", ""Oven"", ""Dishwashe...",--,t,01/04/2023,06/07/2019,13/08/2022,HUTG-014407-15,t
6127,6126,24686418.0,37.0,42.27105,3.14525,6,0.0,2.0,3.0,$44.00,...,1 bath,2.0,"[""Pool"", ""Kitchen"", ""Iron"", ""Air conditioning""...",--,t,01/04/2023,21/08/2021,21/08/2021,HUTG-021036,t
6993,6992,28910213.0,4.0,41.6869,2.81042,8,0.0,4.0,6.0,$180.00,...,2 baths,4.0,"[""Beach essentials"", ""Carbon monoxide alarm"", ...",--,t,01/04/2023,14/04/2019,05/03/2023,HUTG-011673,f
7331,7330,31030020.0,65.0,41.80501,3.05996,5,0.0,2.0,5.0,$146.00,...,1 bath,2.0,"[""Hair dryer"", ""Kitchen"", ""Pool"", ""Washer"", ""P...",--,t,01/04/2023,27/06/2021,07/08/2021,ATG000076,t
7405,7404,30922655.0,129.0,42.21443,3.09584,6,0.0,2.0,5.0,$131.00,...,1.5 baths,2.0,"[""Kitchen"", ""Iron"", ""Washer"", ""BBQ grill"", ""Fr...",--,t,31/03/2023,--,--,HUTG-027264,t
7867,7866,32863501.0,82.0,41.87571,3.0621,8,0.0,4.0,5.0,"$1,000.00",...,3 baths,4.0,"[""Pool"", ""Kitchen"", ""Oven"", ""Washer"", ""Free pa...",--,t,01/04/2023,27/06/2021,27/06/2021,HUTG-022012,t

In [88]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("filtro9españa.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro9españa.csv")

##host_response_time sea "within an hour"

In [82]:
filtro10=df[df["host_response_time"] == "within an hour"]
filtro10

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,14551.0,1.0,41.9965,2.83646,2,0.0,1.0,1.0,$42.00,...,1 private bath,1.0,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",--,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
5,5,751997.0,12.0,41.91798,3.16419,4,0.0,1.0,2.0,$105.00,...,1 bath,1.0,"[""Air conditioning"", ""Pack ’n play/Travel crib...",--,t,01/04/2023,03/05/2016,26/02/2023,HUTG-016218,t
6,6,752035.0,12.0,41.91801,3.17085,4,0.0,2.0,2.0,$110.00,...,1 bath,2.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",--,t,31/03/2023,02/07/2013,31/10/2021,HUTG-008974,f
8,8,45400.0,1.0,41.95577,3.21096,4,0.0,1.0,2.0,$83.00,...,1 bath,1.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""E...",--,t,01/04/2023,28/12/2010,04/03/2023,HUTG-015895,t
10,10,753604.0,7.0,41.7173,2.86409,6,0.0,3.0,4.0,$195.00,...,1 bath,3.0,"[""Carbon monoxide alarm"", ""Free parking on pre...",--,t,01/04/2023,08/09/2013,03/09/2022,LLG-000010,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19648,19647,858355000000000000.0,25.0,41.99906,3.19485,5,0.0,3.0,4.0,$136.00,...,2 baths,3.0,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",--,t,01/04/2023,--,--,HUTG-037880,t
19649,19648,858361000000000000.0,51.0,41.72036,2.92986,4,0.0,1.0,4.0,$107.00,...,1 bath,1.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",--,t,01/04/2023,--,--,HUTG-027601,t
19651,19650,858387000000000000.0,34.0,41.957265,3.201288,8,0.0,4.0,0.0,$209.00,...,5 baths,4.0,"[""Pets allowed"", ""Smoking allowed"", ""Essentials""]",--,t,01/04/2023,--,--,HUTG-001292,t
19652,19651,858396000000000000.0,3.0,41.69907,2.84408,4,0.0,1.0,1.0,$52.00,...,1 bath,1.0,"[""Kitchen"", ""Pets allowed"", ""Washer""]",--,t,01/04/2023,--,--,HUTG019727,t
19654,19653,858418000000000000.0,111.0,41.809375,3.05391,4,0.0,2.0,3.0,$108.00,...,1 bath,2.0,"[""Refrigerator"", ""Microwave"", ""Elevator"", ""Pet...",--,t,01/04/2023,--,--,HUTG-065236,t

In [83]:
#Convertir archivo filtrado a CSV
filtro10.to_csv("filtro10españa.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro10españa.csv")