<a href="https://colab.research.google.com/github/valeriamedina2/Evaluacion/blob/main/filtro_mexico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Filtro Mexico

In [1]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Leemos el codigo 
df= pd.read_csv("valores_nulos_mexico.csv")
df

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,2056638,3,19.35353,-99.16299,3.0,0.0,1.0,1.0,"$1,434.00",...,1.5 baths,1.0,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",--,t,2023-03-30,2014-01-03,2018-06-24,0.0,f
1,1,2072354,3,19.35358,-99.16948,2.0,0.0,1.0,1.0,$830.00,...,1 bath,1.0,"[""Free street parking"", ""Cleaning products"", ""...",--,t,2023-03-30,2014-01-01,2022-11-04,0.0,f
2,2,696037,4,19.44180,-99.18402,6.0,0.0,3.0,3.0,"$1,469.00",...,2 baths,3.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",--,t,2023-03-29,2012-10-31,2022-12-21,0.0,f
3,3,35797,1,19.38283,-99.27178,2.0,0.0,1.0,1.0,"$3,658.00",...,1 bath,1.0,"[""Wifi"", ""Washer"", ""BBQ grill"", ""Indoor firepl...",--,t,2023-03-29,--,--,0.0,f
4,4,44616,16,19.41162,-99.17794,14.0,0.0,5.0,8.0,"$18,000.00",...,5.5 baths,5.0,"[""Free street parking"", ""Security cameras on p...",--,t,2023-03-30,2011-11-09,2023-03-26,0.0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3517,3517,22422552,9,19.43784,-99.14078,4.0,0.0,1.0,1.0,"$1,135.00",...,1 bath,1.0,"[""BBQ grill"", ""Long term stays allowed"", ""TV w...",--,t,2023-03-30,2017-12-29,2018-12-08,0.0,f
3518,3518,22786735,1,19.39708,-99.17802,4.0,0.0,2.0,2.0,$979.00,...,2 baths,2.0,"[""Ethernet connection"", ""Smoke alarm"", ""Single...",--,t,2023-03-30,2018-02-05,2023-03-19,0.0,f
3519,3519,22422562,7,19.39075,-99.15942,2.0,0.0,1.0,1.0,$433.00,...,1 bath,1.0,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",--,t,2023-03-29,2018-01-08,2023-03-12,0.0,f
3520,3520,22714371,1,19.35681,-99.15275,4.0,0.0,2.0,2.0,$878.00,...,1 bath,2.0,"[""Free street parking"", ""Long term stays allow...",--,t,2023-03-29,2018-02-24,2020-08-08,0.0,f
3521,3521,22715728,2,19.30000,0.00000,0.0,0.0,0.0,0.0,0,...,--,0.0,0,--,0,0,--,--,0.0,0

##host_acceptance_rate>50%

In [3]:
#No se encuentra esa columnas

##Solo los registros con la categoria "host_is_superhost"

In [4]:
filtro2=df[df["host_is_superhost"] == "t"]
filtro2

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
2,2,696037,4,19.44180,-99.18402,6.0,0.0,3.0,3.0,"$1,469.00",...,2 baths,3.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",--,t,2023-03-29,2012-10-31,2022-12-21,0.0,f
6,6,56074,2,19.43977,-99.15605,2.0,0.0,1.0,1.0,$650.00,...,1 bath,1.0,"[""Luggage dropoff allowed"", ""Long term stays a...",--,t,2023-03-29,2011-04-02,2023-01-21,0.0,f
7,7,61792,2,19.41083,-99.18057,2.0,0.0,1.0,1.0,"$1,089.00",...,1 shared bath,1.0,"[""Heating - split type ductless system"", ""Whir...",--,t,2023-03-30,2017-11-01,2022-12-31,0.0,f
8,8,704779,13,19.43103,-99.14661,2.0,0.0,1.0,1.0,$943.00,...,1 bath,1.0,"[""Ethernet connection"", ""TV with standard cabl...",--,t,2023-03-29,2013-08-21,2023-02-27,0.0,f
9,9,728372,6,19.44222,-99.14461,16.0,0.0,10.0,16.0,"$2,561.00",...,5.5 baths,10.0,"[""Free street parking"", ""TV with standard cabl...",--,t,2023-03-29,2012-10-31,2023-02-17,0.0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3504,3504,22160411,13,19.43324,-99.14531,7.0,0.0,3.0,5.0,"$1,364.00",...,2 baths,3.0,"[""Smoke alarm"", ""Pool"", ""Crib"", ""Essentials"", ...",--,t,2023-03-29,2017-12-16,2023-03-14,0.0,f
3505,3505,22161120,4,19.44026,-99.15361,3.0,0.0,1.0,2.0,$630.00,...,1 bath,1.0,"[""Luggage dropoff allowed"", ""Shared patio or b...",--,t,2023-03-30,2017-12-13,2023-03-17,0.0,t
3514,3514,22775040,1,19.44155,-99.13216,2.0,0.0,1.0,1.0,$327.00,...,1 shared bath,1.0,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Wi...",--,t,2023-03-29,2018-02-10,2023-03-18,0.0,t
3517,3517,22422552,9,19.43784,-99.14078,4.0,0.0,1.0,1.0,"$1,135.00",...,1 bath,1.0,"[""BBQ grill"", ""Long term stays allowed"", ""TV w...",--,t,2023-03-30,2017-12-29,2018-12-08,0.0,f
3518,3518,22786735,1,19.39708,-99.17802,4.0,0.0,2.0,2.0,$979.00,...,2 baths,2.0,"[""Ethernet connection"", ""Smoke alarm"", ""Single...",--,t,2023-03-30,2018-02-05,2023-03-19,0.0,f

In [6]:
#Convertir archivo filtrado a CSV
filtro2.to_csv("filtro2mexico.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro2mexico.csv")

##"not identity_verified"

In [8]:
filtro3=df[df["host_identity_verified"] == "f"]
filtro3

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,2056638,3,19.35353,-99.16299,3.0,0.0,1.0,1.0,"$1,434.00",...,1.5 baths,1.0,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",--,t,2023-03-30,2014-01-03,2018-06-24,0.0,f
21,21,131610,3,19.35416,-99.16488,2.0,0.0,1.0,1.0,"$1,244.00",...,1 private bath,1.0,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",--,t,2023-03-29,--,--,0.0,f
61,61,276504,1,19.38061,-99.12729,2.0,0.0,0.0,1.0,"$1,815.00",...,1 bath,0.0,"[""Elevator"", ""Wifi"", ""Washer"", ""Kitchen"", ""Poo...",--,f,2023-03-30,--,--,0.0,f
68,68,291804,1,19.36305,-99.15412,1.0,0.0,1.0,1.0,$545.00,...,1 bath,1.0,"[""Kitchen"", ""Smoking allowed"", ""Dryer"", ""Washer""]",--,t,2023-03-30,--,--,0.0,f
70,70,298873,1,19.43358,-99.14452,4.0,0.0,2.0,2.0,"$1,362.00",...,2 baths,2.0,"[""Elevator"", ""Wifi"", ""Oven"", ""Iron"", ""Washer"",...",--,t,2023-03-30,2012-04-19,2019-11-03,0.0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3479,3479,22655094,1,19.21655,-98.99792,4.0,0.0,2.0,2.0,$300.00,...,2 baths,2.0,"[""Private entrance"", ""Wifi"", ""Hot water"", ""Lon...",--,t,2023-03-29,--,--,0.0,t
3484,3484,22124911,6,19.34189,-99.12820,1.0,0.0,0.0,1.0,"$1,500.00",...,1 bath,0.0,[],--,t,2023-03-30,--,--,0.0,f
3501,3501,22160300,1,19.40420,-99.16538,2.0,0.0,1.0,1.0,$800.00,...,1 shared bath,1.0,"[""Extra pillows and blankets"", ""Private entran...",--,t,2023-03-30,2019-02-26,2022-11-26,0.0,f
3508,3508,22700005,4,19.29244,-99.14580,2.0,0.0,2.0,2.0,$590.00,...,1 shared bath,2.0,"[""Private entrance"", ""Wifi"", ""Refrigerator"", ""...",--,t,2023-03-29,2018-03-08,2023-02-27,0.0,f
3520,3520,22714371,1,19.35681,-99.15275,4.0,0.0,2.0,2.0,$878.00,...,1 bath,2.0,"[""Free street parking"", ""Long term stays allow...",--,t,2023-03-29,2018-02-24,2020-08-08,0.0,f

In [9]:
#Convertir archivo filtrado a CSV
filtro3.to_csv("filtro3mexico.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro3mexico.csv")

##property_type = "Private room' y 'Hotel Room"

In [10]:
filtro4=df[df["property_type"] == "Private room"]
#filtro4=df[df["property_type"] == "Hotel Room"]
filtro4

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
21,21,131610,3,19.354160,-99.164880,2.0,0.0,1.0,1.0,"$1,244.00",...,1 private bath,1.0,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",--,t,2023-03-29,--,--,0.0,f
1062,1062,12271259,1,19.390573,-99.129798,2.0,0.0,1.0,2.0,$748.00,...,1 private bath,1.0,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",--,t,2023-03-29,2017-05-23,2022-11-21,0.0,f
2670,2670,19639981,1,19.341660,-99.150350,1.0,0.0,1.0,1.0,$181.00,...,1 shared bath,1.0,"[""Wifi"", ""Breakfast"", ""Washer"", ""Smoking allow...",--,t,2023-03-29,2023-02-26,2023-02-26,0.0,t
2805,2805,20089283,1,19.311520,-99.223410,2.0,0.0,1.0,2.0,$400.00,...,2 shared baths,1.0,"[""Elevator"", ""Extra pillows and blankets"", ""Et...",--,t,2023-03-29,2017-08-10,2023-03-07,0.0,t
3065,3065,21067896,2,19.457330,-99.212270,2.0,0.0,1.0,1.0,$600.00,...,1 shared bath,1.0,"[""Smoke alarm"", ""Shared gym nearby"", ""Luggage ...",--,t,2023-03-30,2017-12-12,2023-01-13,0.0,f
3257,3257,21765818,1,19.434870,-99.187680,2.0,0.0,1.0,1.0,$508.00,...,1 private bath,1.0,"[""Private entrance"", ""Wifi"", ""Washer"", ""Hanger...",--,t,2023-03-30,2017-12-03,2023-03-19,0.0,t
3359,3359,22230184,28,19.413640,-99.162920,2.0,0.0,1.0,1.0,$765.00,...,1 private bath,1.0,"[""Smoke alarm"", ""Free street parking"", ""Single...",--,t,2023-03-30,2017-12-23,2023-03-25,0.0,f
3372,3372,22247072,28,19.415380,-99.160640,2.0,0.0,1.0,1.0,$822.00,...,1 private bath,1.0,"[""Smoke alarm"", ""Free street parking"", ""HDTV w...",--,t,2023-03-30,2017-12-21,2023-03-19,0.0,f
3455,3455,22340146,3,19.433000,-99.141010,2.0,0.0,1.0,1.0,$375.00,...,1 shared bath,1.0,"[""Wifi"", ""Luggage dropoff allowed"", ""Dishes an...",--,t,2023-03-30,2018-01-02,2021-11-27,0.0,f

In [11]:
#Convertir archivo filtrado a CSV
filtro4.to_csv("filtro4mexico.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro4mexico.csv")

##bathroom>1

In [12]:
#Filtro por comparacion
filtro5=df[df["bathrooms"] > 1]
filtro5

Empty DataFrame
Columns: [Unnamed: 0, id, host_listings_count, latitude, longitude, accommodates, bathrooms, bedrooms, beds, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, availability_365, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, id.1, listing_url, scrape_id, last_scraped, source, name, description, neighborhood_overview, picture_url, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_is_superhost, host_thumbnail_url, host_picture_url, host_neighbourhood, host_verifications, host_has_profile_pic, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, property_type, room_type, bathrooms.1, bathrooms_text, bedrooms.1, amenities, calendar_updated.1, has_availability, calendar_last_scraped, first_review, last_review, license, instant_bookable]
Index: []

[0 rows x 77 columns]

In [13]:
#Convertir archivo filtrado a CSV
filtro5.to_csv("filtro5mexico.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro5mexico.csv")

##Precio mayor de 10000 y que sean de tipo "Entire Home"

In [14]:
filtro6=df[(df["price"] > "10000") & (df["room_type"] == "Entire Home/apt")]
filtro6

Empty DataFrame
Columns: [Unnamed: 0, id, host_listings_count, latitude, longitude, accommodates, bathrooms, bedrooms, beds, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, availability_365, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, id.1, listing_url, scrape_id, last_scraped, source, name, description, neighborhood_overview, picture_url, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_is_superhost, host_thumbnail_url, host_picture_url, host_neighbourhood, host_verifications, host_has_profile_pic, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, property_type, room_type, bathrooms.1, bathrooms_text, bedrooms.1, amenities, calendar_updated.1, has_availability, calendar_last_scraped, first_review, last_review, license, instant_bookable]
Index: []

[0 rows x 77 columns]

In [15]:
#Convertir archivo filtrado a CSV
filtro6.to_csv("filtro7mexico.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro7mexico.csv")

##registros review_scores_cleanliness>4.5

In [17]:
filtro7=df[df["review_scores_cleanliness"] > 4.5]
filtro7

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,2056638,3,19.35353,-99.16299,3.0,0.0,1.0,1.0,"$1,434.00",...,1.5 baths,1.0,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",--,t,2023-03-30,2014-01-03,2018-06-24,0.0,f
1,1,2072354,3,19.35358,-99.16948,2.0,0.0,1.0,1.0,$830.00,...,1 bath,1.0,"[""Free street parking"", ""Cleaning products"", ""...",--,t,2023-03-30,2014-01-01,2022-11-04,0.0,f
2,2,696037,4,19.44180,-99.18402,6.0,0.0,3.0,3.0,"$1,469.00",...,2 baths,3.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",--,t,2023-03-29,2012-10-31,2022-12-21,0.0,f
4,4,44616,16,19.41162,-99.17794,14.0,0.0,5.0,8.0,"$18,000.00",...,5.5 baths,5.0,"[""Free street parking"", ""Security cameras on p...",--,t,2023-03-30,2011-11-09,2023-03-26,0.0,f
5,5,2075738,1,19.41909,-99.16043,2.0,0.0,1.0,1.0,"$2,561.00",...,2 baths,1.0,"[""BBQ grill"", ""Luggage dropoff allowed"", ""TV w...",--,t,2023-03-29,2014-02-05,2023-02-27,0.0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3515,3515,22420437,63,19.43052,-99.18718,6.0,0.0,3.0,5.0,"$3,631.00",...,3.5 baths,3.0,"[""Smoke alarm"", ""Free street parking"", ""Single...",--,t,2023-03-30,2018-01-05,2023-01-04,0.0,t
3516,3516,22706422,3,19.43608,-99.16877,2.0,0.0,1.0,1.0,"$1,200.00",...,1 bath,1.0,"[""Ethernet connection"", ""Smoke alarm"", ""Luggag...",--,t,2023-03-30,2021-08-23,2021-12-11,0.0,t
3517,3517,22422552,9,19.43784,-99.14078,4.0,0.0,1.0,1.0,"$1,135.00",...,1 bath,1.0,"[""BBQ grill"", ""Long term stays allowed"", ""TV w...",--,t,2023-03-30,2017-12-29,2018-12-08,0.0,f
3518,3518,22786735,1,19.39708,-99.17802,4.0,0.0,2.0,2.0,$979.00,...,2 baths,2.0,"[""Ethernet connection"", ""Smoke alarm"", ""Single...",--,t,2023-03-30,2018-02-05,2023-03-19,0.0,f
3520,3520,22714371,1,19.35681,-99.15275,4.0,0.0,2.0,2.0,$878.00,...,1 bath,2.0,"[""Free street parking"", ""Long term stays allow...",--,t,2023-03-29,2018-02-24,2020-08-08,0.0,f

In [18]:
#Convertir archivo filtrado a CSV
filtro7.to_csv("filtro6mexico.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro6mexico.csv")

##registros review_scores_value>4.9

In [20]:
filtro8=df[df["review_scores_value"] > 4.9]
filtro8

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
10,10,2083241,7,19.41530,-99.16763,3.0,0.0,1.0,2.0,"$1,881.00",...,1 bath,1.0,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",--,t,2023-03-30,2014-10-03,2023-03-13,0.0,f
11,11,67703,3,19.41152,-99.16857,4.0,0.0,2.0,2.0,"$2,088.00",...,1 bath,2.0,"[""Record player"", ""Extra pillows and blankets""...",--,t,2023-03-30,2011-11-17,2023-01-01,0.0,f
13,13,70644,3,19.35448,-99.16217,2.0,0.0,1.0,1.0,"$1,097.00",...,1 bath,1.0,"[""Smoke alarm"", ""Free street parking"", ""Luggag...",--,t,2023-03-29,2012-02-14,2023-01-31,0.0,f
24,24,783080,3,19.33009,-99.21418,1.0,0.0,1.0,1.0,$549.00,...,1.5 baths,1.0,"[""Extra pillows and blankets"", ""Wifi"", ""Iron"",...",--,t,2023-03-29,2015-06-26,2023-03-26,0.0,f
26,26,2118573,3,19.38777,-99.17532,6.0,0.0,3.0,4.0,"$2,049.00",...,3 baths,3.0,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Si...",--,t,2023-03-30,2014-01-31,2023-03-02,0.0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3509,3509,22775016,1,19.44367,-99.20695,2.0,0.0,1.0,2.0,$835.00,...,1 bath,1.0,"[""Free street parking"", ""Luggage dropoff allow...",--,t,2023-03-30,2018-03-11,2018-03-31,0.0,f
3511,3511,22705737,1,19.33373,-99.20319,4.0,0.0,2.0,3.0,"$1,000.00",...,2 baths,2.0,"[""Smoke alarm"", ""399\"" HDTV with premium cable...",--,t,2023-03-29,2018-02-25,2022-12-04,0.0,f
3513,3513,22419330,1,19.42670,-99.16514,2.0,0.0,1.0,1.0,"$1,900.00",...,1 bath,1.0,"[""Smoke alarm"", ""Pool"", ""Essentials"", ""Oven"", ...",--,t,2023-03-30,2019-04-21,2020-03-06,0.0,f
3516,3516,22706422,3,19.43608,-99.16877,2.0,0.0,1.0,1.0,"$1,200.00",...,1 bath,1.0,"[""Ethernet connection"", ""Smoke alarm"", ""Luggag...",--,t,2023-03-30,2021-08-23,2021-12-11,0.0,t
3517,3517,22422552,9,19.43784,-99.14078,4.0,0.0,1.0,1.0,"$1,135.00",...,1 bath,1.0,"[""BBQ grill"", ""Long term stays allowed"", ""TV w...",--,t,2023-03-30,2017-12-29,2018-12-08,0.0,f

In [21]:
#Convertir archivo filtrado a CSV
filtro8.to_csv("filtro8mexico.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro8mexico.csv")

##availability_365<100

In [22]:
filtro9=df[df["availability_365"] < 100]
filtro9

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
2,2,696037,4,19.44180,-99.18402,6.0,0.0,3.0,3.0,"$1,469.00",...,2 baths,3.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",--,t,2023-03-29,2012-10-31,2022-12-21,0.0,f
21,21,131610,3,19.35416,-99.16488,2.0,0.0,1.0,1.0,"$1,244.00",...,1 private bath,1.0,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",--,t,2023-03-29,--,--,0.0,f
26,26,2118573,3,19.38777,-99.17532,6.0,0.0,3.0,4.0,"$2,049.00",...,3 baths,3.0,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Si...",--,t,2023-03-30,2014-01-31,2023-03-02,0.0,f
37,37,187030,6,19.41057,-99.17730,2.0,0.0,1.0,1.0,"$50,000.00",...,1 bath,1.0,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",--,t,2023-03-30,2011-11-01,2023-03-15,0.0,f
38,38,187745,6,19.41057,-99.17730,3.0,0.0,1.0,2.0,"$5,000.00",...,2 baths,1.0,"[""Wifi"", ""Washer"", ""Free street parking"", ""Hos...",--,t,2023-03-30,2013-11-10,2018-01-03,0.0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3493,3493,22389032,2,19.41268,-99.18099,2.0,0.0,1.0,0.0,$370.00,...,1 shared bath,1.0,"[""Dedicated workspace"", ""Private entrance"", ""W...",--,t,2023-03-30,2018-01-15,2023-03-14,0.0,t
3495,3495,22145704,7,19.43086,-99.20313,6.0,0.0,3.0,5.0,"$1,700.00",...,1 bath,3.0,"[""Luggage dropoff allowed"", ""Long term stays a...",--,t,2023-03-30,2017-12-30,2022-12-30,0.0,f
3498,3498,22676559,2,19.47440,-99.06481,2.0,0.0,2.0,1.0,$280.00,...,2 baths,2.0,"[""Extra pillows and blankets"", ""Smoke alarm"", ...",--,t,2023-03-29,2018-03-13,2020-11-01,0.0,t
3503,3503,22692095,1,19.39480,-99.16786,1.0,0.0,1.0,1.0,$400.00,...,1 bath,1.0,"[""Private entrance"", ""Wifi"", ""Iron"", ""Washer"",...",--,t,2023-03-30,--,--,0.0,f
3521,3521,22715728,2,19.30000,0.00000,0.0,0.0,0.0,0.0,0,...,--,0.0,0,--,0,0,--,--,0.0,0

In [23]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("filtro9mexico.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro9mexico.csv")

##host_response_time sea "within an hour"

In [24]:
filtro10=df[df["host_response_time"] == "within an hour"]
filtro10

,Unnamed: 0,id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
2,2,696037,4,19.44180,-99.18402,6.0,0.0,3.0,3.0,"$1,469.00",...,2 baths,3.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",--,t,2023-03-29,2012-10-31,2022-12-21,0.0,f
4,4,44616,16,19.41162,-99.17794,14.0,0.0,5.0,8.0,"$18,000.00",...,5.5 baths,5.0,"[""Free street parking"", ""Security cameras on p...",--,t,2023-03-30,2011-11-09,2023-03-26,0.0,f
6,6,56074,2,19.43977,-99.15605,2.0,0.0,1.0,1.0,$650.00,...,1 bath,1.0,"[""Luggage dropoff allowed"", ""Long term stays a...",--,t,2023-03-29,2011-04-02,2023-01-21,0.0,f
7,7,61792,2,19.41083,-99.18057,2.0,0.0,1.0,1.0,"$1,089.00",...,1 shared bath,1.0,"[""Heating - split type ductless system"", ""Whir...",--,t,2023-03-30,2017-11-01,2022-12-31,0.0,f
8,8,704779,13,19.43103,-99.14661,2.0,0.0,1.0,1.0,$943.00,...,1 bath,1.0,"[""Ethernet connection"", ""TV with standard cabl...",--,t,2023-03-29,2013-08-21,2023-02-27,0.0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3515,3515,22420437,63,19.43052,-99.18718,6.0,0.0,3.0,5.0,"$3,631.00",...,3.5 baths,3.0,"[""Smoke alarm"", ""Free street parking"", ""Single...",--,t,2023-03-30,2018-01-05,2023-01-04,0.0,t
3517,3517,22422552,9,19.43784,-99.14078,4.0,0.0,1.0,1.0,"$1,135.00",...,1 bath,1.0,"[""BBQ grill"", ""Long term stays allowed"", ""TV w...",--,t,2023-03-30,2017-12-29,2018-12-08,0.0,f
3518,3518,22786735,1,19.39708,-99.17802,4.0,0.0,2.0,2.0,$979.00,...,2 baths,2.0,"[""Ethernet connection"", ""Smoke alarm"", ""Single...",--,t,2023-03-30,2018-02-05,2023-03-19,0.0,f
3519,3519,22422562,7,19.39075,-99.15942,2.0,0.0,1.0,1.0,$433.00,...,1 bath,1.0,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",--,t,2023-03-29,2018-01-08,2023-03-12,0.0,f
3520,3520,22714371,1,19.35681,-99.15275,4.0,0.0,2.0,2.0,$878.00,...,1 bath,2.0,"[""Free street parking"", ""Long term stays allow...",--,t,2023-03-29,2018-02-24,2020-08-08,0.0,f

In [25]:
#Convertir archivo filtrado a CSV
filtro10.to_csv("filtro10mexico.csv")
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("filtro10mexico.csv")